import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Page from "./page";
import clsx from "clsx"; // Import the 'clsx' function

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Site CV Axel ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      
            <body className={clsx(inter.className, "h-full")}>
              {children}
            </body>
    </html>
  );
}
